url: http://octopress.org
//https://github.com/luerhouhou/DriveFriendStu_ios.git
markdown: redcarpet
exclude:
  - Gemfile
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
minify_html: false
